Repository 24f2003068/hactoberfest25, pull requests merged in 2025-10, with the labels that each got.

#1 Implement various algorithms and data structures across multiple week…
  graded_pa/week_1/Goldbach's cojecture.py
  graded_pa/week_1/min_diff_bw_2_lists_same.py
  graded_pa/week_1/odd_dtat_type_inlist.py
  graded_pa/week_2/combination_sort.py
  graded_pa/week_2/count_occurance.py
  graded_pa/week_2/find_largest_by_rotation.py
  graded_pa/week_2/listunion.py
  graded_pa/week_2/merge_in_place.py
  graded_pa/week_2/missingnumber.py
  graded_pa/week_3/dish_prepare_order.py
  graded_pa/week_3/reverse_root_node.py
  graded_pa/week_3/stack_evaluation_expression.py
  graded_pa/week_4/findConnectionLevel.py
  graded_pa/week_4/findMasterTank.py
  graded_pa/week_4/longJourney.py
  graded_pa/week_5/FiberLink.py
  graded_pa/week_5/isNegativeWeightCyclePresent.py
  graded_pa/week_5/min_cost_walk.py
  graded_pa/week_6/maxLessThan.py
  graded_pa/week_6/merge_k_list.py
  graded_pa/week_6/min_max_heap.py
  graded_pa/week_7/insertAVLTree.py
  graded_pa/week_7/minimumPlatfromTrainSchedule.py
  graded_pa/week_7/noOverlap.py
  graded_pa/week_8/MoM7pos.py
  graded_pa/week_8/counterintersection.py
  graded_pa/week_8/findOCCof.py
  graded_pa/week_8/minDistancePoints.py
  graded_pa/week_9/constructWord.py
  graded_pa/week_9/longest_decreasing_sequence.py
  graded_pa/week_9/maxCoinsPath.py
Labels: good first issue, Hactoberfest-accepted

#3 Implement various algorithms including binary search, sorting in rang… Issue #2
  practice_pa/week_1/binarysearchindex_andcomparison.py
  practice_pa/week_1/sort_in_range_complexity.py
  practice_pa/week_1/triangle_class.py
  practice_pa/week_1/twin_primes.py
  practice_pa/week_2/binarysaerchindex_comparisons.py
  practice_pa/week_2/sort_in_range.py
  practice_pa/week_3/doubly_linked_list.py
  practice_pa/week_3/quadratic.py
  practice_pa/week_4/findAllPaths.py
  practice_pa/week_4/find_componentsUndirected_graph.py
  practice_pa/week_4/maze_solver.py
  practice_pa/week_5/class_XYZ_courier.py
  practice_pa/week_5/min_cost_routeMap.py
  practice_pa/week_6/HeapSort.py
  practice_pa/week_6/KMinGreaterThan.py
  practice_pa/week_6/connectCamp.py
  practice_pa/week_7/huffman.py
  practice_pa/week_7/minimizeLateness.py
  practice_pa/week_8/karatsuba__calculateAndAssign.py
  practice_pa/week_8/kthLargets.py
  practice_pa/week_9/maxProfit.py
  practice_pa/week_9/maxValueItems.py
Labels: enhancement, Hactoberfest-accepted, hactoberfest2025-accepted

#4 Implement various algorithms and data structures across multiple week…
  livecodingsolutions/week_1/del_chars.py
  livecodingsolutions/week_1/expanding.py
  livecodingsolutions/week_1/histogram.py
  livecodingsolutions/week_1/list_two_shuffle.py
  livecodingsolutions/week_1/prime_product.py
  livecodingsolutions/week_1/sumsquare_listoddeven.py
  livecodingsolutions/week_2/deck_subordinate.py
  livecodingsolutions/week_2/findCommonElements.py
  livecodingsolutions/week_2/findLPairSum.py
  livecodingsolutions/week_2/findPeak.py
  livecodingsolutions/week_3/doubly_linked_list_part2.py
  livecodingsolutions/week_3/mergesortedlists.py
  livecodingsolutions/week_3/removeduplicate.py
  livecodingsolutions/week_3/stack_queue.py
  livecodingsolutions/week_4/backAndForth.py
  livecodingsolutions/week_4/coolWorkers.py
  livecodingsolutions/week_4/minimumHops.py
  livecodingsolutions/week_5/Airport.py
  livecodingsolutions/week_5/bets_fare.py
  livecodingsolutions/week_5/min_transmissionTime.py
  livecodingsolutions/week_6/Type_of_heep.py
  livecodingsolutions/week_6/find_kth_largest_root.py
  livecodingsolutions/week_6/find_redundant_edges.py
  livecodingsolutions/week_7/decode.py
  livecodingsolutions/week_7/is_code_valid.py
  livecodingsolutions/week_7/max_value_selection.py
  livecodingsolutions/week_8/find_rotation_count.py
  livecodingsolutions/week_8/kth_element.py
  livecodingsolutions/week_8/median.py
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest

#5 Implement programs to retrieve ISBN numbers and referee names based o…
  ope_python/ques8.py
  ope_python/ques9.py
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest

#6 Add SQL queries for retrieving team and player information across mul…
  ope_sql/ques_1.sql
  ope_sql/ques_2.sql
  ope_sql/ques_3.sql
  ope_sql/ques_4.sql
  ope_sql/ques_5.sql
  ope_sql/ques_6.sql
  ope_sql/ques_7.sql
Labels: enhancement, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest

#7 Add: Update README and CONTRIBUTING files for Hacktoberfest 2025, and…
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest

#9 PR 1
  oops_cpp/five.cpp
  oops_cpp/four.cpp
  oops_cpp/one.cpp
  oops_cpp/three.cpp
  oops_cpp/two.cpp
Labels: good first issue, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest

#8 Create word_frequency_csv.py
  word_frequency_csv.py
Labels: enhancement, good first issue, Hacktoberfest-accepted, hacktoberfest2025-accepted, hacktoberfest
